### ISSUE TITLE
BSD and do not redistribute

### ISSUE THREAD

**Issue by basxto** [Miner28/Bronze-Mod#5]
What is the point of using a BSD license and then disallowing people to share the mod in any form?
Forking alone would violate this.

**Comment by Miner28** [comment]
The text in README.txt is something i forgot in there.

**Comment by Miner28** [comment]
This was in there because some people just downloaded the mod and then were distrubuting it and were saying that its theirs mod. Which i did not like soo that's why i licenced the mod soo i can maybe make them to either not distribute it or mention me.
